version: '3.8'
services:
  student-service:
    container_name: student-service
    build:
      context: student-service
    restart: always
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_HOST: mongo
    healthcheck:
      test: "exit 0"
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2.10
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
#    volumes:
#      - $HOME/mongo:/data/db
    healthcheck:
      test: "exit 0"
